[mongodb]
mongodb-dev.devopstest.fun

[catalogue]
catalogue-dev.devopstest.fun

[redis]
redis-dev.devopstest.fun

[user]
user-dev.devopstest.fun

[cart]
cart-dev.devopstest.fun

[mysql]
mysql-dev.devopstest.fun

[rabbitmq]
rabbitmq-dev.devopstest.fun

[shipping]
shipping-dev.devopstest.fun

[payment]
payment-dev.devopstest.fun

[all:vars]
ansible_user="ec2-user"
ansible_password="DevOps321"
MONGODB_HOST=mongodb-dev.devopstest.fun
CATALOGUE_HOST=catalogue-dev.devopstest.fun
REDIS_HOST=redis-dev.devopstest.fun
USER_HOST=user-dev.devopstest.fun
CART_HOST=cart-dev.devopstest.fun
MYSQL_HOST=mysql-dev.devopstest.fun
RABBITMQ_HOST=rabbitmq-dev.devopstest.fun
SHIPPING_HOST=shipping-dev.devopstest.fun
PAYMENT_HOST=payment-dev.devopstest.fun
