- name: creating mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: Installing mongodb
    ansible.builtin.dnf:
      name: mongodb-org
      state: present

  - name: allow remote connections
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: enable and restart mongod
    ansible.builtin.service:
      state: restarted
      enabled: yes
